### ISSUE TITLE
Feedback from naive user

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#12]
Took my first look at `roblog` and trying to use it to submit a draft post.

Context: I'm now fairly comfortable with my workflow based on [these instructions](https://github.com/ropensci/roweb2#contributing-a-blog-post) except that I work on a branch, not a fork. I use those instructions to guide first-time post submitters. I'm not yet comfortable/versatile with diverging from that workflow, whereas someone who has had a package go through onboarding won't have the same perceptions. I use RStudio just once in a while while trying to learn stuff and don't yet fully get "project" setup etc

- what does `roblog` aim to make simpler/better for an author of a blog post or tech note compared with the current instructions? Can you add that statement near top of README?
- I was able to follow https://github.com/ropenscilabs/roblog#r-markdown-templates to create a blog post template (...after starting new session 🤪)
- my habit in trying a thing for the first time is to scan the README then start executing things from the top. After scanning, I wasn't sure what my minimal starting materials had to be
  - e.g. do I start with creating a new blog post R Markdown template in RStudio? but maybe I should [create a post project](https://github.com/ropenscilabs/roblog#create-a-post-project) first? or do I set up my directories to suit `Fork helper` so my files are in the right place? 
- Tried `Create a post project`. I wasn't convinced I needed a post draft for that.
  - `Error in create_post_project(tempdir(), "test", "2018-10-15", type = "Rmd",  : 
  could not find function "create_post_project"`

**Comment by maelle** [comment]
Thank you, this is very valuable feedback!

**Comment by maelle** [comment]
Closing this because the workflow recommendations will probably change (but they'll need testing too ;-)).
