### ISSUE TITLE
Make template headings appropriate size

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#13]
RStudio R Markdown blog post template has `# Section` and `## Subsection`. Best to change to `### Section` and `#### Subsection` or whatever is appropriate

**Comment by maelle** [comment]
I think now it's fine to have `#` and `##` in blog posts because Jeroen changed their sizes, will check. Eventually actually I want to go through all old posts to homogeneize the user of header levels! (with some sort of script :-) ).

**Comment by maelle** [comment]
Now done
