### ISSUE TITLE
How to customize images

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#16]
Alignment, size etc.

Cf https://github.com/ropensci/roweb2/pull/551#issuecomment-554788641

**Comment by maelle** [comment]
https://yihui.org/knitr/hooks/

**Comment by maelle** [comment]
@cderv @rlesur I'll implement something based on your minimal working example, is it ok if I add you both as ctb of this package when I do?

**Comment by RLesur** [comment]
No problem. Thanks!

**Comment by cderv** [comment]
No problem too. Thank you!

**Comment by maelle** [comment]
Fixed by #24
