### ISSUE TITLE
Support spell checks?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#17]
When one uses `spelling` there's a way to ignore words (e.g. rOpenSci is not a typo). Where do we keep the words list and how do we update it?

In roweb2? And the PR adding a blog post would also add new exceptions?

**Comment by maelle** [comment]
For illustrating the problem

``` r
path <- "/home/maelle/R/x86_64-pc-linux-gnu-library/3.6/roblog/examples/bad-no-alt.md"
spelling::spell_check_files(path)
#>   WORD         FOUND IN
#> gists        bad-no-alt.md:58
#> img          bad-no-alt.md:42,44
#> md           bad-no-alt.md:20
#> png          bad-no-alt.md:42,44
#> ropensci     bad-no-alt.md:54
#> Ropensci     bad-no-alt.md:54
#> roweb        bad-no-alt.md:20
#> shortcode    bad-no-alt.md:40,58
#> shortcodes   bad-no-alt.md:58
#> src          bad-no-alt.md:42,44
#> Vimeo        bad-no-alt.md:58
#> YAML         bad-no-alt.md:30
#> Youtube      bad-no-alt.md:58
spelling::spell_check_files(path, ignore = c("gists","img",
                                             "md", "png",
                                             "roweb", "shortcode",
                                             "shortcodes", "src",
                                             "Vimeo", "YAML",
                                             "Youtube"))
#>   WORD       FOUND IN
#> ropensci   bad-no-alt.md:54
#> Ropensci   bad-no-alt.md:54
```

<sup>Created on 2019-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Where do we keep the values for ignore?

**Comment by maelle** [comment]
An alternative is NOT supporting this in any way, and instead have an item in the check list that asks authors whether they did use any tool for spell checking 

* `spelling::spell_check_files()`

* RStudio https://stackoverflow.com/questions/36728061/how-can-i-use-spell-check-in-rmarkdown

**Comment by stefaniebutland** [comment]
> alternative is NOT supporting this in any way

I can see the challenge of needing to maintain a long list of values for ignore.

Main motivation is fact that there are english typos in 99.5% of posts. And I only catch and correct these manually. Wondering best way to handle this

**Comment by maelle** [comment]
A topic for our next call

**Comment by maelle** [comment]
The latest RStudio version will have live spell checking. Maybe a check box in a check list "I used RStudio or another tool to look for typos" rather than creating a tool in roblog?

**Comment by stefaniebutland** [comment]
> a check box in a check list "I used RStudio or another tool to look for typos" rather than creating a tool in roblog?

agreed. 
I opened this issue Add checklist item for spellcheck using RStudio or other tool #103
