### ISSUE TITLE
Tags checking

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#20]
Per https://github.com/ropenscilabs/roblog/issues/3#issuecomment-559275370

- [ ] check for specific tags required for specific types of posts

Not all of these could be automated

e.g. 
- R
- packages (e.g. use if YAML has `package_version:`, but also in some other cases)
- Software Peer Review (for pkg that passed peer review, or for use of dev guide)
- community (question: would we use this for posts written by at least one non-staff member? Currently [#community tag](https://ropensci.org/tags/community/) is for many things - community-contributed package; unconf or similar community-oriented posts; community calls  
- topic labels from software peer review submission OR tags = package categories from our Packages page

**Comment by maelle** [comment]
Do we want some automatic checks, or an item in a check list?

**Comment by stefaniebutland** [comment]
item in a checklist is probably best
