### ISSUE TITLE
Check for links to reviewers and review thread

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#23]
Acknowledge reviewers by listing their full name, linked to their online presence, such as GitHub, Twitter, or personal website. Link to software peer review thread for your package.

**Comment by maelle** [comment]
related to #9

**Comment by maelle** [comment]
@stefaniebutland is this included in blog-guidance?

**Comment by maelle** [comment]
this is included in a check list. @stefaniebutland do you think we could detect this automatically or can I close the issue?

**Comment by stefaniebutland** [comment]
ok to close.
No need to add automatic detection imo.
