### ISSUE TITLE
Add function checking blog post

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#3]
Input: path to .md blog post.

What it'd do: 

- [ ] spell check, 

- [x] checking there is an alt text by figure (and indicating to use fig.cap otherwise), 

- [x] checking the links (relative links, actual URLs with `crul::ok`)

- [ ] if possible checking the functions are `function()`

Digest other stuff from https://r-resources.massey.ac.nz/rmarkdown/ in the function and put the rest in guidelines in the README of this repo.

**Comment by maelle** [comment]
related to https://github.com/ropensci/roweb2/issues/463

**Comment by stefaniebutland** [comment]
- [ ] check if they're using Hugo shortcodes e.g. for images, tweets

**Comment by stefaniebutland** [comment]
- [ ] capitalization as rOpenSci not ROpenSci

**Comment by stefaniebutland** [comment]
- [ ] check for specific tags required for specific types of posts

Not all of these could be automated

e.g. 
- R
- packages (e.g. use if YAML has `package_version:`, but also in some other cases)
- Software Peer Review (for pkg that passed peer review, or for use of dev guide)
- community (question: would we use this for posts written by at least one non-staff member? Currently [#community tag](https://ropensci.org/tags/community/) is for many things - community-contributed package; unconf or similar community-oriented posts; community calls  
- topic labels from software peer review submission OR tags = package categories from our Packages page

**Comment by maelle** [comment]
will close in favor of more specific issues
