### ISSUE TITLE
Links for packages

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#31]
Recommend the use of the docs.ropensci.org URL (and to ensure the GitHub URL is in DESCRIPTION thus accessible from the pkgdown website).

cc @jeroen

**Comment by maelle** [comment]
@stefaniebutland should this become part of the style guide? I.e. "when linking to rOpenSci packages I used their docs.ropensci.org URL" or so?

**Comment by stefaniebutland** [comment]
added to style guide commit Mar 2nd.

**Comment by maelle** [comment]
thank you!
