### ISSUE TITLE
Pre-submission checklists

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#33]
We should discuss what goes in the checklists https://github.com/ropenscilabs/roblog/blob/master/inst/checklists/submission-checklist.csv

especially to decide how short or long the checklist needs to be. Maybe the editor's checklist should be the long one, with one item per post component.

I suggest adding this:
I have read the Technical Guidelines.

**Comment by maelle** [comment]
To be tackled in the bookdown repo.
