### ISSUE TITLE
Broken links to templates in roblog

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#34]
reported by Kari Norman in https://github.com/ropensci/roweb2/pull/609#issuecomment-583565764

**Comment by maelle** [comment]
@karinorman sorry to bother you but what exactly failed i.e. which function (or trying to create a Rmd from R RStudio menu?)?

**Comment by stefaniebutland** [comment]
At https://docs.ropensci.org/roblog/reference/blog-posts.html
Link to templates is broken in the line: "Call them via the add-in or directly or get the templates online."
