### ISSUE TITLE
Installation instruction in README errors

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/roblog#35]
`install.packages("roblog", repos = "https://dev.ropensci.org")` results in

```
Warning in install.packages :
  package ‘roblog’ is not available (for R version 3.6.3 RC)
```

**Comment by maelle** [comment]
I'll switch to remotes then, thank you!

**Comment by pat-s** [comment]
Are you maintaining a drat repo for ropensci helper pkgs which is missing the entry for roblog?

**Comment by maelle** [comment]
not a drat repo, but yep I'll have things to explore in this realm.
