### ISSUE TITLE
Feature request: Function to create folder structure and open new Rmd/md file

### ISSUE THREAD

**Issue by steffilazerte** [ropenscilabs/roblog#37]
An idea for a helper function:

Function would take a publication date and slug name, then create the folder in `content/blog` and a start a draft `date-slug.Rmd` or `date-slug.md` file in that folder from the template?

**Comment by maelle** [comment]
That's a neat idea, I'd need to look into blogdown's New Post addin.

**Comment by maelle** [comment]
Related, #26

**Comment by maelle** [comment]
Maybe I should move the md and Rmd templates to roweb2 cf https://gohugo.io/content-management/archetypes/

**Comment by maelle** [comment]
[blogdown addin source](https://github.com/rstudio/blogdown/blob/master/inst/scripts/new_post.R)

**Comment by maelle** [comment]
https://github.com/rstudio/blogdown/pull/432

**Comment by stefaniebutland** [comment]
I like Steffi's suggestion.

Regarding:
> We'd also need something creating the author file after creating the post.

Since many will already have an author file, maybe leave this as a manual step?

**Comment by maelle** [comment]
It'd only create if it doesn't exist, and that'd be rather easy once the rest is done. 🙂

**Comment by maelle** [comment]
(Well if I find out how to automate folder naming... which would be great)

**Comment by maelle** [comment]
@steffilazerte once we can use the blogdown New Post Addin for roweb2, I was thinking of simply removing the roblog functions that access the templates.

The ways to get the templates would be
* copy-paste from the blog guide (Markdown) or GitHub (R Markdown) and save the file under the correct path.
* use blogdown New Post Addin in roweb2. It's very good, it can guess your name, and based on the title + date creates the correct folder with index.Rmd or index.md + it lets you choose tags from existing tags.

So if one doesn't use RStudio, one will need to do the manual stuff.

**Comment by maelle** [comment]
See https://bookdown.org/yihui/blogdown/rstudio-ide.html to see how the addin looks like.

**Comment by steffilazerte** [comment]
Pretty slick :)

**Comment by maelle** [comment]
Yes, it makes my current work (replacing the authors param with an author param...) worth it :sweat_smile:
