### ISSUE TITLE
Updated templates in blog guidance

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/roblog#38]
Looks like you get these from same source, but noting here just in case. Ok to close this issue if no roblog update needed.

In [this PR](https://github.com/ropensci-org/blog-guidance/pull/107), changed YAML `description` to add length. `description: "A very short summary of your post (~ 100 characters)"`

**Comment by maelle** [comment]
Thanks, yes I get them from there but I'll let this open since I'll soon move the templates from blog-guidance to roweb2. :dizzy_face:
