### ISSUE TITLE
ro_lint_md() incorrectly identifies problems with sentence case

### ISSUE THREAD

**Issue by steffilazerte** [ropenscilabs/roblog#41]
`ro_lint_md()` identifies problems with sub headings that have extra punctuation (i.e. ?, -, /) and identifies this as a problem with sentence case.

For example, the headings...

- "Accessible highlighting?" is suggested to be "Accessible highlighting"
- "Server-side syntax highlighting" is suggested to be "Server side syntax highlighting"
- "Produce line-highlighted code blocks with glue/paste0" is suggested to be "Produce line highlighted code blocks with glue paste0"

**Comment by maelle** [comment]
Good catch, thanks!

Less false positive now I think

``` r
roblog::ro_lint_md("/home/maelle/Documents/ropensci/roweb2/content/technotes/2020-04-30-code-highlighting/index.md")
#> * Use Sentence case for headings i.e. "On chroma options for line highlighting", "Knitr hook to highlight lines of source code", "Produce line-highlighted code blocks with glue/paste 0". (Ignore this note if the words are proper nouns)
#> 
#> * Please write rOpenSci in lower camelCase, not: ropensci, ropensci.
#> 
#> A bit more work is needed on this ace post draft!
```

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
