### ISSUE TITLE
Function creating the excerpt for discuss

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#6]
Input: Path to Markdown post

function creating the excerpt and URL for the discuss post (easy to create that URL from info in the YAML)

**Comment by maelle** [comment]
@stefaniebutland for you such a function might more useful if it took the URL as input as well, correct?

**Comment by maelle** [comment]
Ideally the function would post to discuss https://github.com/sckott/discgolf, get the topicid, add it to the roweb2 file via GitHub API.

It'd start by checking the URL is ok.

It could take the PR number as input instead of the URL.

@stefaniebutland would you use the function and if so what would you prefer inputting?

**Comment by maelle** [comment]
This might never be needed if the Discourse integration becomes automatic. cc @sckott

**Comment by sckott** [comment]
right, have it on my to do list to look at again, will let you all know soon

**Comment by maelle** [comment]
This issue itself is outdated, the discussion about Discourse is in https://github.com/ropensci-org/blog-guidance/issues/30
