### ISSUE TITLE
Helper to deploy locally?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/roblog#8]
I do deploy locally these days, maybe some authors will do that (but they don't have to, if they don't want to install Hugo locally).

**Comment by maelle** [comment]
```r
p <- processx::process$new("hugo", args = "server", echo = TRUE)
Sys.sleep(120)
localhost <- "http://localhost:1313"
browseURL(localhost)
p$kill()
```

**Comment by maelle** [comment]
And a mention of blogdown's helper to install Hugo.

**Comment by stefaniebutland** [comment]
I def prefer it if people preview locally. 
Don't know, though, how much a helper is needed

https://5e309b628ac2c8b21b4ef9f6--ropensci-blog-guidance.netlify.com/technical.html#submit-your-draft-post

**Comment by maelle** [comment]
yeah no helper is needed I think
